### ISSUE TITLE
can you measure web2py too?

### ISSUE THREAD

**Issue by sharkguto** [klen/py-frameworks-bench#16]
can you measure web2py too on your benchmarks?

**Comment by Tset-Noitamotua** [comment]
Why is web2py not included?

**Comment by gi0baro** [comment]
@sharkguto @Tset-Noitamotua web2py still doesn't provide complete python 3 support, these benchmarks are python 3 only.

**Comment by Tset-Noitamotua** [comment]
thanks for info
