### ISSUE TITLE
Missing requests/s metric

### ISSUE THREAD

**Issue by sk-** [klen/py-frameworks-bench#5]
The benchmark is missing the number of requests/s. I ran a similar test as the JSON one, and yes `flask` is faster than `aiohttp` with those `wrk` settings. However, `aiohttp` handles more than 11 times more requests as `flask`. 4098 vs 359 in my case.

**Comment by klen** [comment]
In my tests last aiohttp handles 78043 vs 129463 from flask for 20 seconds  JSON test. Did you use gunicorn with `meinheld.gmeinheld.MeinheldWorker ` for Flask?

**Comment by sk-** [comment]
Thanks for pointing out the right worker to use. Will try it.
